language: perl

env:
  - AUTOMATED_TESTING=1 PREREQS="rlib File::HomeDir File::Spec Array::Columnize Data::Dumper Getopt::Long Digest::SHA Pod::Text Syntax::Highlight::Perl::Improved Scalar::Util PadWalker"
  - AUTOMATED_TESTING=1 PREREQS="Devel::Callsite Term::ReadLine::Perl5 Data::Printer B::CodeLines Eval::WithLexicals rlib File::HomeDir File::Spec Array::Columnize Data::Dumper Getopt::Long Digest::SHA Pod::Text Syntax::Highlight::Perl::Improved Scalar::Util PadWalker"

install:
  # Prerequisites
  - "cpanm $PREREQS"

perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
