---
abstract: 'Modular Perl Debugger (akin to Ruby "Trepanning" Debuggers).'
author:
  - 'Rocky Bernstein <rocky@cpan.org>'
build_requires:
  Test::More: '0.81'
  Time::HiRes: '1.9721'
  rlib: '0.02'
configure_requires:
  Module::Build: '0.4214'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-Trepan
no_index:
  package:
    - SelfLoader
    - DB
    - Carp
recommends:
  B::CodeLines: '1.1'
  Data::Dumper::Concise: '0'
  Data::Printer: '0'
  Devel::Trepan::Deparse: v2.1.0
  Devel::Trepan::Disassemble: '1.9'
  Devel::Trepan::Shell: v1.4.1
  Eval::WithLexicals: '0'
  Pod::Text::Color: '2.06'
  Term::ReadLine::Perl5: '1.33'
requires:
  Array::Columnize: '1.04'
  Data::Dumper: '0'
  Devel::Callsite: '0.08'
  Digest::SHA: '0'
  File::HomeDir: '0.54'
  Getopt::Long: '2.36'
  PadWalker: '0'
  Pod::Text: '3.13'
  Scalar::Util: '0'
  Syntax::Highlight::Perl::Improved: '1.01'
  perl: '5.008008'
  rlib: '0.02'
  version: '0'
resources:
  bugtracker: https://github.com/rocky/Perl-Devel-Trepan/issues
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/rocky/Perl-Devel-Trepan
version: '0.73'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
